@startuml createVerifiableCredential

title  Create Verifiable Credential\n

start
:Input **ICreateVerifiableCredentialArgs**;
:Extract issuer did (string) from **ICreateVerifiableCredentialArgs**;
:Get issuer did;
note right
  * Issuer DID contains key to sign
  * Issuer DID is retrieved from DIDStore
end note
partition CreateJWT {
  :Create JSON web signature (JWS);
  note right
    * Content to create **JWS** consists of **encoded credential payload**
    * Use private key from Issuer DID to sign
  end note
  :Return JWT;
}

:Normalize created JWT to W3C credential format;
stop

@enduml